[package]
name = "d2021"
publish = false
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[lints]
workspace = true

[dependencies]
itertools = "0.13.0"
md5 = "0.7.0"
rayon = "1.10.0"
regex = "1.10.4"
thiserror = "1.0.58"

daocutil = { path = "../daocutil" }
