[package]
name = "d2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
daocutil = { version = "0.1.0", path = "../daocutil" }
itertools = "0.13.0"
nu-ansi-term = "0.50.1"
regex = "1.11.1"
thiserror = "2.0.3"

[lints]
workspace = true
