[package]
name = "d2015"
publish = false
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[lints]
workspace = true

[dependencies]
itertools = "0.12.0"
md5 = "0.7.0"
regex = "1.10.2"
thiserror = "1.0.50"
